### ISSUE TITLE
implements JsonSerializable interface

### ISSUE THREAD

**Issue by wahwahid** [scheb/yahoo-finance-api#10]
How if we applying implementation of JsonSerializable interface on every Result Classes in order to support json_encode() of the result data ?

**Comment by loekvangool** [comment]
Would love that, personally.

**Comment by scheb** [comment]
What about this? https://github.com/scheb/yahoo-finance-api/tree/serializable

**Comment by wahwahid** [comment]
Yeah, that.

**Comment by scheb** [comment]
Done. New release 2.1.0.
