### ISSUE TITLE
Yahoo Finance API is not available.

### ISSUE THREAD

**Issue by Bukashk0zzz** [scheb/yahoo-finance-api#11]
Hi,

Thanks for this library. 
When I send request get back error

Yahoo Finance API is not available.

<img width="895" alt="screen shot 2017-08-31 at 16 35 59" src="https://user-images.githubusercontent.com/1908342/29925919-84b5264a-8e6a-11e7-8848-3cc7546c9802.png">

**Comment by scheb** [comment]
This is because the Yahoo Finance API is in fact very unstable at the moment. I didn't get any succesful build for several days now and there are multiple complaints on the internet (e.g. StackOverflow) of people having the same issue.

**Comment by scheb** [comment]
Seems to be stable again.
