### ISSUE TITLE
getQuote() fails

### ISSUE THREAD

**Issue by shlomnissan** [scheb/yahoo-finance-api#14]
Hey :)

`getQuote()` seems to throw back the following error:

`PHP Warning:  array_map(): Argument #2 should be an array in /Applications/MAMP/htdocs/asxlink/vendor/scheb/yahoo-finance-api/src/ResultDecoder.php`

even though the unofficial API's are still active.

`search()` and `getHistoricalData()` are still working fine.

**Comment by scheb** [comment]
Are you using version 2 oder 3?

**Comment by shlomnissan** [comment]
Yes, sorry, I was using version 2 :/

Thank you very much for all your help and prompt response :)
