### ISSUE TITLE
Could not extract crumb from response

### ISSUE THREAD

**Issue by schirrmie** [scheb/yahoo-finance-api#15]
Hi,

I'll get the folllowing error while getting historical data.

#4 {main}exception 'Scheb\YahooFinanceApi\Exception\ApiException' with message 'Could not extract crumb from response' in /vendor/scheb/yahoo-finance-api/src/ResultDecoder.php:128
Stack trace:
#0 /vendor/scheb/yahoo-finance-api/src/ApiClient.php(77): Scheb\YahooFinanceApi\ResultDecoder->extractCrumb('<!DOCTYPE html>...')

**Comment by scheb** [comment]
Might happen, when the response is not valid/complete for some reason. You could implement a retry feature for such a case.
