### ISSUE TITLE
Is it possible to return the last day of the month?

### ISSUE THREAD

**Issue by recoverjp** [scheb/yahoo-finance-api#20]
If I use "getHistoricalData (..., INTERVAL_1_MONTH, ..., ...)", it returns the first day of the month. Is it possible to return the last day?

**Comment by scheb** [comment]
Hey @recoverjp, I must have missed your question unfortunately.

I don't think this is supported by the API. What you can do is fetching the last day for each month individually or just the whole time frame with daily interval and skip everything but the last day of each month.
