### ISSUE TITLE
Expand the readme file

### ISSUE THREAD

**Issue by luisdev** [scheb/yahoo-finance-api#22]
The readme file is extremely technical. Please expand the usage instructions so that people who are not familiar with Composer can still use this tool.

Can you use this code outside of Composer?

**Comment by scheb** [comment]
Yes, you can. Download the library and add it to your project, but then you have to take care yourself of the autoloading.

If you're not using Composer or PSR-style autoloading, please do so. It's the de-facto industry standard how PHP libraries are managed. To learn about Composer, go to https://getcomposer.org/

It's not the libarary's job to teach how to use it.
