### ISSUE TITLE
How do we get just a single object value from the returned object?

### ISSUE THREAD

**Issue by RCTORONTO** [scheb/yahoo-finance-api#25]

**Comment by scheb** [comment]
Sorry, I don't understand your question. Can you provide an example?

**Comment by RCTORONTO** [comment]
Hi, Thanks for replying, yes I shoud have been more specific.

So we like for example:

we have

$quotes = $client -> getQuotes ([$_GET['sym']]);

or

$quote = $client -> getQuote($sym);

if I print_r on the returned object I get something like

"Array ( [0] => Scheb\YahooFinanceApi\Results\Quote Object ( [ask:Scheb\YahooFinanceApi\Results\Quote:private] => 20.4 [askSize:Scheb\YahooFinanceApi\Results\Quote:private] => [averageDailyVolume10Day:Scheb\YahooFinanceApi\Results\Quote:private] => 3649125 [averageDailyVolume3Month:Scheb\YahooFinanceApi\Results\Quote:private] => 4579286"

how do I get the ask price for example from this object?

$quote[0]['ask'] ?
$quote[0]['ask:Scheb\YahooFinanceApi\Results\Quote:private']

I don't understand how to extract the data items  - I've tried json_decoding, array casting, for each loops, nothing seems to output just the "20.4" ask price I'm looking for.

Ryan








________________________________

**Comment by scheb** [comment]
Well, the `Scheb\YahooFinanceApi\Results\Quote` indicates it is an object and not an array. Sounds like you haven't worked that much with objects or PHP yet. Here's a good overview how objects work and how to read object property values: https://www.learn-php.org/en/Objects

**Comment by RCTORONTO** [comment]
Yes I am a bit uh new on more advanced programming concepts like Object classes etc, Arrays, serializing things (recently I ran into an issue understanding that I couldn't serialize a file descriptor trying to pass ancillary messages to pass a socket in another php script).

I figured it out in actually looking at your code 🙂  - I can now do things like "echo $quote->getAsk();"

turns out I was thinking I could just access the private properties of the class object.  whoops.

Thanks very much for sharing this and for your reply.

Ryan








________________________________
