### ISSUE TITLE
why is env => datatables needed to build query in creaturl?

### ISSUE THREAD

**Issue by matzke** [scheb/yahoo-finance-api#3]
do i need to pass this parameter? is there an alternative, when datatables org is down!?

`````` php

createUrl($query)
    {
        $params = array(
            'env' => "http://datatables.org/alltables.env",
            'format' => "json",
            'q' => $query,
        );
        return "http://query.yahooapi
}```
``````

**Comment by scheb** [comment]
I don't remember any more, what this parameter is for. Has been a while since I create that library. If you find a way to do queries without that parameter, feel free to send me a PR.

**Comment by Taronyuu** [comment]
@scheb, you may want to close this issue since it confused me. I just forked your repository to update the env parameter until I saw that you already did that 5 days ago. 😄

**Comment by scheb** [comment]
Jep, they seemed to have changed the call, I've seen it when my stock panel didn't work any more. So I updated it recently.

**Comment by Taronyuu** [comment]
Yeah same here, we lost a lot of data unfortunately. The current call doesn't return nearly as much as the previous one. However nothing we can do about it.
