### ISSUE TITLE
WKN / ISIN

### ISSUE THREAD

**Issue by ChristianWorkman** [scheb/yahoo-finance-api#31]
Gibt es auch die Möglichkeit über die WKN zu suchen?

Wenn man nach dem Namen einer Aktien sucht, wäre es auch gut wenn im Ergebnis zusätzlich die ISIN stehen würde. Ist das möglich?

**Comment by scheb** [comment]
Beziehst du dich damit auf die `search` Methode der Library?

**Comment by ChristianWorkman** [comment]
Ich habe es mit $searchResult = $client->search("Apple"); probiert. 
Name, symbol und ISIN finden hier Ergebnisse, die WKN aber nicht

**Comment by scheb** [comment]
Dann werden wohl keine WKNs unterstützt. Yahoo Finance ist nun mal eine US-amerikanische Seite, daher unwahrscheinlich dass sie sich für die deutsche WKN interessieren.
