### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'Scheb\YahooFinanceApi\ApiClientFactory' not found

### ISSUE THREAD

**Issue by thebolet** [scheb/yahoo-finance-api#32]
Hello,

I have a problem. I installed scheb using composer commands (note that I'm not with it). 
So I did
`composer require scheb/yahoo-finance-api
`

And 
`composer update scheb/yahoo-finance-api
`

Then I created a test.php in my root folder with : 

```php
<?php
use Scheb\YahooFinanceApi\ApiClient;
use Scheb\YahooFinanceApi\ApiClientFactory;
use GuzzleHttp\Client;

// Create a new client from the factory
$client = ApiClientFactory::createApiClient();



// Returns an array of Scheb\YahooFinanceApi\Results\SearchResult
$searchResult = $client->search("Apple");

// Returns an array of Scheb\YahooFinanceApi\Results\HistoricalData
$historicalData = $client->getHistoricalQuoteData(
    "AAPL",
    ApiClient::INTERVAL_1_DAY,
    new \DateTime("-14 days"),
    new \DateTime("today")
);

print_r($historicalData);exit; ?>
```

But i got the following errors : 
`Fatal error: Uncaught Error: Class 'Scheb\YahooFinanceApi\ApiClientFactory' not found in C:\wamp64\www\index.php on line 9`
`( ! ) Error: Class 'Scheb\YahooFinanceApi\ApiClientFactory' not found in C:\wamp64\www\index.php on line 9`

Can you help me please ?

**Comment by scheb** [comment]
Did you forget to include Composer's [autoloader](https://getcomposer.org/doc/01-basic-usage.md#autoloading)?

**Comment by thebolet** [comment]
You're right, I was using wrong path ! Thank you
