### ISSUE TITLE
Question: Is it possible to query information on German stocks with the API?

### ISSUE THREAD

**Issue by krisztianb** [scheb/yahoo-finance-api#37]
**Description**

So basically the script is calling the following REST endpoint to get its data: https://query1.finance.yahoo.com/v7/finance/quote?symbols=GOOG

Which works perfectly all right for US stocks. But when I use the symbol of let's say Adidas which is ADS I get no result:

https://query1.finance.yahoo.com/v7/finance/quote?symbols=ADS

Any ideas what I am missing?

**Comment by scheb** [comment]
Yes you can, if you use the symbols that are used on Yahoo Finance. Best found through the search feature on site.

E.g. `ADS.DE` gives you the Frankfurt Xetra data: https://query1.finance.yahoo.com/v7/finance/quote?symbols=ADS.DE

**Comment by krisztianb** [comment]
Great. Thank you.
