### ISSUE TITLE
getQuotes is failing with "Unauthorized"

### ISSUE THREAD

**Issue by scheb** [scheb/yahoo-finance-api#38]
This is reminder to myself, that since today Yahoo Finance API started to error with "Unauthorized" when trying to fetch quotes data.

**Comment by abdallas** [comment]
Any ideas as to when it may get resolved?  Read somewhere that Yahoo is now requiring passing of an explicit crumb field.
Thank you.

**Comment by abdallas** [comment]
So looks like you need to do this:
https://query1.finance.yahoo.com/v1/test/getcrumb
and use the returned value in you subsequent call for example:
https://query1.finance.yahoo.com/v7/finance/quote?symbols=%5ESPX%2C%5EIXIC%2C%5EDJI&crumb=7PGf4eHpHoy

No idea how long that crumb is valid.

**Comment by cbeyer** [comment]
Using this excellent bundle, I would love to have the resolution of this problem

**Comment by abdallas** [comment]
As a temp fix I pointed it to use v6 of the query url and it appears to work for now.  Not sure what the difference is between v6 & v7.
Since I only use fetchQuotes function modified ApiClient.php in /scheb/yahoo-finance-api/src line 224 to use v6.

**Comment by filippotoso** [comment]
It's working again.

**Comment by scheb** [comment]
The issue reappeared. Published v4.6.0 release to solve this issue.

Details: https://github.com/scheb/yahoo-finance-api/issues/39#issuecomment-1537419916
