### ISSUE TITLE
Invalid Cookie

### ISSUE THREAD

**Issue by jqueryhacker** [scheb/yahoo-finance-api#39]
https://github.com/scheb/yahoo-finance-api)

HI, Thank you so much for the work yu have done to keep  Yahoo finance accessible. I don't have the version no for this script. I have been running it successfuly for several  years but today it failed as follows.

 Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://query1.finance.yahoo.com/v7/finance/quote?symbols=%5EIXIC%2C%5EDJI%2C%5EGSPC%2C%5ERUT%2CAKRO%2CAQN%2CBCRX%2CBTAI%2CCCOI%2CCOCO%2CGPOR%2CGRBK%2CHEAR%2CPAGS%2CTFX` resulted in a `401 Unauthorized` response:
{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}

Your help  would be very much appreciated.

**Comment by vikrampant** [comment]
Getting same today ... curious if Yahoo! finally shut this off.  But will monitor thread.

**Comment by scheb** [comment]
Yahoo Finance API had the same issue some days ago, see https://github.com/scheb/yahoo-finance-api/issues/38. Last time, the issue just vanished after a few days.

At this point it's still unclear if this is just a temporary thing again or if this is the new status quo 🤷

As mentioned in the readme, the API endpoints used from Yahoo Finance are unofficial, so things like this are to be expected.

**Comment by scheb** [comment]
A v6 endpoint is still live and returning seemingly identical data (did not check in detail).

The v7 endpoint is now protected by a `crumb` value _and_ requires valid session cookies to be initialized from Yahoo Finance website. In addition, seemingly depending on location, GDPR consent needs to be given on Yahoo Finance website to generate a valid session, that is allowed to query the API. Tried to figure out what needs to be done, to script this process, it's terribly complicated. Switching to v6 seems to be the better solution.

Published v4.6.0 release to solve this issue. Let's see how long this keeps working.
