### ISSUE TITLE
V6 API endpoint 404

### ISSUE THREAD

**Issue by brightq** [scheb/yahoo-finance-api#40]
**Package version**: 4.6.0

**Description**

When using the getQuotes(array $symbols) function, it throw out the following error
```
  Client error: `GET https://query1.finance.yahoo.com/v6/finance/quote?symbols=%5ERUT` resulted in a `404 Not Found` response:
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}
```

**To Reproduce**

1. Create a new APIClient instance
2. call $client->getQuotes(["^RUT"])
3. See error

```
   GuzzleHttp\Exception\ClientException 

  Client error: `GET https://query1.finance.yahoo.com/v6/finance/quote?symbols=%5ERUT` resulted in a `404 Not Found` response:
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}

  at vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
    109▕         if ($summary !== null) {
    110▕             $message .= ":\n{$summary}\n";
    111▕         }
    112▕ 
  ➜ 113▕         return new $className($message, $request, $response, $previous, $handlerContext);
    114▕     }
    115▕ 
    116▕     /**
    117▕      * Obfuscates URI if there is a username and a password present


```

**Additional Context**

This stopped working about 5 hrs ago (Tuesday, May 23, 2023 10:30:00 PM UTC)
Was working with out any problem before that.

**Comment by yasinaslan16** [comment]
+1 .  We have to get crumb

https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python

1. Make HTTP GET call to URL https://fc.yahoo.com/. Although this call result in a 404 error, we just need it to extract set-cookie from response headers which is then used in the subsequent calls

2. Now make an HTTP GET call to the URL https://query2.finance.yahoo.com/v1/test/getcrumb, by including the obtained cookie from the previous response headers. This call will retrieve the crumb value.

3. Replace [crumb-value] in the following URL and make a HTTP GET call with cookie [https://query2.finance.yahoo.com/v7/finance/quote?symbols=TSLA&crumb=[crumb-value]](https://query2.finance.yahoo.com/v7/finance/quote?symbols=TSLA&crumb=%5Bcrumb-value%5D)

4. Cache the cookie value and crumb value to skip first two steps going forward

**Comment by nevets963** [comment]
This is the code I'm using that works in place of the current `fetchQuotes` method where it makes multiple HTTP requests, however, is good enough for my usecase where I only need to run this code once a day:

```php
    private function fetchQuotes(array $symbols)
    {
        $cookieJar = new CookieJar();

        $initialUrl = 'https://fc.yahoo.com';
        $this->client->request('GET', $initialUrl, ['cookies' => $cookieJar, 'http_errors' => false]);

        $initialUrl = 'https://query2.finance.yahoo.com/v1/test/getcrumb';
        $crumb = (string) $this->client->request('GET', $initialUrl, ['cookies' => $cookieJar])->getBody();

        $url = 'https://query2.finance.yahoo.com/v7/finance/quote?crumb=' . $crumb . '&symbols='.urlencode(implode(',', $symbols));
        $responseBody = (string) $this->client->request('GET', $url, ['cookies' => $cookieJar])->getBody();

        return $this->resultDecoder->transformQuotes($responseBody);
    }
```

**Comment by scheb** [comment]
@nevets963 Which country are you in? To my knowledge this solution only works from non-GDPR countries.

**Comment by nevets963** [comment]
@scheb I tested this code in both the UK and Germany.

**Comment by ktpx** [comment]
The initial post is about v6 of the API, not v7.  It seems v6 has been shut down.

**Comment by nevets963** [comment]
From what I can tell, V7 returns the same (or near same) response as V6 so is a good alternative.

**Comment by ktpx** [comment]
> From what I can tell, V7 returns the same (or near same) response as V6 so is a good alternative.

Yeah. i think they are compatible.  ive used both.  But v6 required no cookie crap.

**Comment by brightq** [comment]
@nevets963 Thanks, the code with cookie and V7 works well for us.

**Comment by scheb** [comment]
V7 should definitely be compatible since this is what the library used until it stopped working.

I'll check if the tripple request strategy with the crumb is working _reliable_ now. It was not reliable before, that's why I switched to the V6 endpoint.

**Comment by ktpx** [comment]
Does this still work? I just get invalid crumb.  

{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback"}}}⏎ 

We’re sorry for the inconvenience, but API-level access to Yahoo Finance quotes data has been disabled. 

That message doesn't look too promising.

**Comment by scheb** [comment]
@nevets963 @yasinaslan16 Your approach https://github.com/scheb/yahoo-finance-api/issues/40#issuecomment-1561352644 is doing the job. Thanks for sharing!

New version v4.7.0 available.
