### ISSUE TITLE
Yahoo Finance GuzzleHTTP Exception is Recurring on V6 Endpoint

### ISSUE THREAD

**Issue by jqueryhacker** [scheb/yahoo-finance-api#41]
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://query1.finance.yahoo.com/v6/finance/quote?symbols=%5EIXIC%2C%5EDJI%2C%5EGSPC%2C%5ERUT%2CABCL%2CASGN%2CAVO%2CCRCT%2CDEI%2CDINO%2CEPAM%2CGEN%2CGHL%2CINZY%2CLKFN` resulted in a `404 Not Found` response:
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}

**Comment by scheb** [comment]
Please follow the conversation here: https://github.com/scheb/yahoo-finance-api/issues/40

**Comment by scheb** [comment]
Fixed in v4.7.0
