### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by mapelo** [scheb/yahoo-finance-api#43]
"scheb/yahoo-finance-api": "4.x-dev"

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://query2.finance.yahoo.com/v7/finance/download/0P00011HBL.F?period1=1692354296&period2=1692403200&interval=1d&events=history` resulted in a `404 Not Found` response: 404 Not Found: Timestamp data missing

**Comment by scheb** [comment]
This seems to be related to the stock specifically. Getting the data for other stocks works with the same request.

Likely, there's no historical data for that stock for that time frame. That's why the API responds with 404.

**Comment by mapelo** [comment]
The problem occurs, in my case, with investment funds.

But you are right. It was a problem of choosing correct dates with data.

Thank you!!!!
