### ISSUE TITLE
Yahoo! We will right back...

### ISSUE THREAD

**Issue by yasinaslan16** [scheb/yahoo-finance-api#45]
https://fc.yahoo.com/ is problematic because the system is running extremely slow and sometimes gives errors. Has anyone found an alternative solution?
![WhatsApp Image 2023-12-06 at 13 45 22](https://github.com/scheb/yahoo-finance-api/assets/99640389/7d1c6f05-7f90-4153-a603-52184552e40d)

**Comment by vikrampant** [comment]
Haven't found any alternatives yet.  Been same for past few weeks.  I've disabled any use of getQuote/getQuotes.  Tried the historical function but realized using "today" still brings the prior day's close.

**Comment by N1njaWTF** [comment]
I'm wondering about this issue too.. its become extremely slow the past few weeks.

Have you found a solution?

**Comment by vikrampant** [comment]
I tweaked the $initialUrl in ApiClient.php around line 212.  Grabbing that initial cookie from another Yahoo site vs fc.yahoo.

`        
$initialUrl = 'https://sports.yahoo.com';
`

**Comment by scheb** [comment]
I see the issue of slowness with the `fc.yahoo.com` domain as well. Though I haven't found a good alternative yet.

The suggested `sports.yahoo.com` doesn't do it for me, as I'm getting "Invalid Cookie" errors further down the line.

**Comment by vikrampant** [comment]
Forgot to mention I also added another value in the header to the user agent.  I pulled that from other Guzzle-based scripts I've used in the past.

```
public function getHeaders(): array
    {
        return [
            'User-Agent' => $this->userAgent,
            'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        ];
    }
```

**Comment by scheb** [comment]
Thanks for the hint! That gets the call to `sports.yahoo.com` working, but it doesn't initialize an `A3` cookie (`fc.yahoo.com` does). I get a `GUCS` cookie instead and that doesn't seem to be sufficient to retrieve a crumb. Fetching a crumb gets me a error 500 response back.

I believe it has something to do with different locations. Especially in the EU (I'm in Germany) where we have GDPR, you have to accept the terms and conditions to get proper cookies initialized.

**Comment by N1njaWTF** [comment]
did anyone find a solution yet? :) for my tool i programmed, its very unfortunate to have such long loading times when trying to query something from Yahoo Finance..
