### ISSUE TITLE
HTTP 404

### ISSUE THREAD

**Issue by foxbille** [scheb/yahoo-finance-api#46]
not a bug.
when seaching quote for a society whose quotation has ceased, with :
`$quote = $client->getHistoricalQuoteData("KORI.PA",ApiClient::INTERVAL_1_DAY,new \DateTime("2020-02-10"),new \DateTime("today"));`
i get HTTP 404 error, like this :
`Client error: `GET https://query1.finance.yahoo.com/v7/finance/download/KORI.PA?period1=1581289200&period2=1705359600&interval=1d&events=history``
How can i manage this error and thus avoiding php script interrupt during a loop thru list of societies ?
(Error occurs even param "end_date" of GetHistoricalQuoteData is set to cease_date). 
Thanks
Eric

**Comment by scheb** [comment]
You want a try-catch statement to catch the exception, then ignore it and continue with the next item of the for loop.

https://www.w3schools.com/php/php_exception.asp

**Comment by foxbille** [comment]
Have tried it before my post here, but it doesn't work either.
Http 404 is no php error or exception, does it ?
Anyway, tanks for reply. 
Eric
