### ISSUE TITLE
Get Historical Data Parameter Problem

### ISSUE THREAD

**Issue by SeaRoth** [scheb/yahoo-finance-api#5]
$data = $client->getHistoricalData("YHOO");
- Requires more parameters

$start = new DateTime('2014-01-02');
$end = new DateTime('2014-01-05');
$data = $client->getHistoricalData("YHOO",$start,$end);

Fatal error: Uncaught Scheb\YahooFinanceApi\Exception\HttpException: HTTP call failed with error 0

I'm not sure if you're still working on this app, however, thank you for it!

**Comment by scheb** [comment]
Sorry for the late response. Works for me, so I guess it's a HTTP timeout problem. Have you tried increasing the timeout parameter which is available on the ApiClient class?

**Comment by SeaRoth** [comment]
It works for me too -- I have come to the conclusion the Yahoo Finance API was temporarily down during this time.  Thank you for your response.
