### ISSUE TITLE
Directory and class names in lower case

### ISSUE THREAD

**Issue by mgwebgroup** [scheb/yahoo-finance-api#6]
May I suggest to have the directory names and class names to be in lower case? This is needed for `spl_autoload_register()` to be able to find classes inside the directory structure. You already have name spaces matching the directory structure, which is great. Thank you for your code!

**Comment by scheb** [comment]
Sorry, no. The bundle follows the PSR-4 standard for autoloading. If you install the bundle with Composer and use the Composer autoloader, you should have no problems at all.
